services:
# By default, we don't start v0 in development mode
  api-rest-v0:
# To start it manually, run:
# $ docker-compose -f docker-compose.yml -f docker-compose-dev.yml run -d --no-deps --use-aliases --name allmanak_api-rest-v0_manual api-rest-v0 /bin/sh -c "exec postgrest /etc/postgrest.conf"
# To stop it, run:
# $ docker rm -f allmanak_api-rest-v0_manual
# Another option is to comment the 'command: /bin/true' line and run:
# $ docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d api-rest-v0
    command: /bin/true
    environment:
      PGRST_SERVER_PROXY_URI: http://localhost/rest-api/v0/
    restart: on-failure
  api-rest-v1:
    environment:
      PGRST_SERVER_PROXY_URI: http://localhost/rest-api/v1/
    restart: unless-stopped
  app:
    command: sh -c 'yarn && yarn dev'
    expose: ['10000']
    restart: unless-stopped
  build-static:
    command: /bin/true
    restart: on-failure
  db:
    restart: unless-stopped
  fakemail:
    image: mailhog/mailhog:v1.0.0 #check-outdated
    restart: unless-stopped
  import-cron:
    command: /bin/true
    restart: on-failure
  web:
    ports: ['80:80', '10000:10000']
    restart: unless-stopped
    volumes:
      - './nginx/default-dev.conf:/etc/nginx/conf.d/default.conf:ro'
version: '3.1'
